### ISSUE TITLE
fill color and stocks not working only opacity works

### ISSUE THREAD

**Issue by rsa-rajesh** [vs-nascimento/svg_pic_editor#1]

**Comment by vs-nascimento** [comment]
Could you provide me with additional examples of how you identified the error?

**Comment by vs-nascimento** [comment]
For this issue, where "fill color and strokes" weren’t working properly, with only opacity functioning, the fix was implemented in version 2.0.0. In this update, the search and edit system was enhanced to accurately identify and manipulate fill color and stroke properties as reported in issue #1.

With this update, it’s now possible to apply fill and stroke colors directly while keeping the opacity settings as expected.
